baseURL = "https://uwsmphmedstudents-hyde.netlify.com/"
languageCode = "en-us"
theme = "hyde"
title = "UWSMPH Students"
[params]
disqusShortname = ""
googleAnalytics = ""
layoutReverse = false
theme = "hyde"
themeColor = ""
